In [273]:
import pandas as pd
import numpy as np
import time
import datetime
from datetime import datetime, timedelta, timezone
import pytz

In [2]:
activity = pd.read_csv("C:\\Users\\ylin\\Desktop\\ias file\\activity.csv")
impression = pd.read_csv("C:\\Users\\ylin\\Desktop\\ias file\\impressions.csv")

C:\Users\ylin\AppData\Local\Continuum\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2717: DtypeWarning: Columns (9,10) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [3]:
activity.columns

Index(['Event_Time', 'User_ID', 'Advertiser_ID', 'Campaign_ID', 'Site_ID_DCM',
       'Placement_ID', 'Activity_ID', 'DBM_Device_Type', 'DBM_Advertiser_ID',
       'DBM_Attributed_Inventory_Source_Is_Public', 'DBM_Auction_ID',
       'DBM_Insertion_Order_ID', 'DBM_Line_Item_ID', 'Total_Conversions',
       'Total_Revenue', 'DBM_Revenue_Advertiser_Currency'],
      dtype='object')

In [4]:
activity.User_ID.count()

139664

In [5]:
impression.User_ID.count()

632678

In [6]:
impression.User_ID[impression.DBM_Insertion_Order_ID == 3863579].count()

364785

In [7]:
activity.columns

Index(['Event_Time', 'User_ID', 'Advertiser_ID', 'Campaign_ID', 'Site_ID_DCM',
       'Placement_ID', 'Activity_ID', 'DBM_Device_Type', 'DBM_Advertiser_ID',
       'DBM_Attributed_Inventory_Source_Is_Public', 'DBM_Auction_ID',
       'DBM_Insertion_Order_ID', 'DBM_Line_Item_ID', 'Total_Conversions',
       'Total_Revenue', 'DBM_Revenue_Advertiser_Currency'],
      dtype='object')

In [8]:
activity.Activity_ID.unique()

array([ 320052,  320053,  320216,  320217, 6060602, 6065499, 6066102], dtype=int64)

In [9]:
activity['DBM_Insertion_Order_ID'].unique()

array([ 3863580.,  3863579.,       nan])

In [10]:
impression['DBM_Insertion_Order_ID'].unique()

array([3863580, 3863579], dtype=int64)

In [11]:
len(activity.DBM_Auction_ID.unique())

771

In [12]:
len(activity.DBM_Auction_ID)

139664

---

In [113]:
activity2 = pd.read_csv("C:\\Users\\ylin\\Desktop\\ias file\\activity_2.csv")
impression2 = pd.read_csv("C:\\Users\\ylin\\Desktop\\ias file\\impressions_2.csv")

In [114]:
activity2.columns

Index(['Event_User', 'Event_Time', 'User_ID', 'Advertiser_ID', 'Campaign_ID',
       'Site_ID_DCM', 'Placement_ID', 'Activity_ID', 'DBM_Device_Type',
       'DBM_Advertiser_ID', 'DBM_Attributed_Inventory_Source_Is_Public',
       'DBM_Auction_ID', 'DBM_Insertion_Order_ID', 'DBM_Line_Item_ID',
       'Total_Conversions', 'Total_Revenue',
       'DBM_Revenue_Advertiser_Currency'],
      dtype='object')

In [115]:
activity2.Activity_ID.unique()

array([ 320052,  320053,  320216,  320217, 6066102, 6060602, 6065499], dtype=int64)

In [116]:
activity2["measurable_6060602"] = 0
activity2["viewable_6066102"] = 0
activity2["fraud_6065499"] = 0
activity2["HI_Quote_320052"] = 0
activity2["HI_Sales_320053"] = 0

In [117]:
activity2.loc[activity2.Activity_ID == 6060602, "measurable_6060602"] = 1
activity2.loc[activity2.Activity_ID == 6066102, "viewable_6066102"] = 1
activity2.loc[activity2.Activity_ID == 6065499, "fraud_6065499"] = 1
activity2.loc[activity2.Activity_ID == 320052, "HI_Quote_320052"] = 1
activity2.loc[activity2.Activity_ID == 320053, "HI_Sales_320053"] = 1

In [118]:
activity2.head()

Event_User    Event_Time  \
0  1506930000000000_AMsySZY8muPyhRGV3SdWC4l3mo3n  1.506930e+15   
1  1506930000000000_AMsySZamNYBSz1EQrGABbK0ui60a  1.506930e+15   
2  1506930000000000_AMsySZamNYBSz1EQrGABbK0ui60a  1.506930e+15   
3  1506940000000000_AMsySZY63VYQ1DO4K56qEQGpY42f  1.506940e+15   
4  1506940000000000_AMsySZbTfidKErdEJ7P-CnCk1iGN  1.506940e+15   

                        User_ID  Advertiser_ID  Campaign_ID  Site_ID_DCM  \
0  AMsySZY8muPyhRGV3SdWC4l3mo3n        1268443     20334041       984668   
1  AMsySZamNYBSz1EQrGABbK0ui60a        1268443     20334041       984668   
2  AMsySZamNYBSz1EQrGABbK0ui60a        1268443     20334041       984668   
3  AMsySZY63VYQ1DO4K56qEQGpY42f        1268443     20334041       984668   
4  AMsySZbTfidKErdEJ7P-CnCk1iGN        1268443     20334041       984668   

   Placement_ID  Activity_ID  DBM_Device_Type  DBM_Advertiser_ID  \
0     205800991       320052              0.0             3601.0   
1     205801000       320052              0.0             3601.0   
2     205801000       320052              0.0             3601.0   
3     205802575       320052              0.0             3601.0   
4     205802575       320052              0.0             3601.0   

        ...        DBM_Insertion_Order_ID DBM_Line_Item_ID  Total_Conversions  \
0       ...                     3863580.0       13955149.0                  1   
1       ...                     3863579.0       13955138.0                  1   
2       ...                     3863579.0       13955138.0                  1   
3       ...                     3863579.0       13955134.0                  1   
4       ...                     3863579.0       13955134.0                  1   

   Total_Revenue  DBM_Revenue_Advertiser_Currency  measurable_6060602  \
0       0.000175                                0                   0   
1       0.000324                                0                   0   
2       0.000389                                0                   0   
3       0.000240                                0                   0   
4       0.000157                                0                   0   

   viewable_6066102  fraud_6065499  HI_Quote_320052  HI_Sales_320053  
0                 0              0                1                0  
1                 0              0                1                0  
2                 0              0                1                0  
3                 0              0                1                0  
4                 0              0                1                0  

[5 rows x 22 columns]

In [122]:
activity2.viewable_6066102.sum()/activity2.measurable_6060602.sum()

0.7403115043349116

In [123]:
activity2.measurable_6060602.sum()/len(activity2.viewable_6066102)

0.5640608889907206

In [141]:
activity2.pivot_table(index="Event_User", values=["measurable_6060602","viewable_6066102", "HI_Sales_320053", "HI_Quote_320052"], aggfunc=np.sum).sort_values("HI_Quote_320052", ascending=False).to_csv("C:\\Users\\ylin\\Desktop\\ias file\\"+"ias stats.csv")

In [143]:
activity2.columns

Index(['Event_User', 'Event_Time', 'User_ID', 'Advertiser_ID', 'Campaign_ID',
       'Site_ID_DCM', 'Placement_ID', 'Activity_ID', 'DBM_Device_Type',
       'DBM_Advertiser_ID', 'DBM_Attributed_Inventory_Source_Is_Public',
       'DBM_Auction_ID', 'DBM_Insertion_Order_ID', 'DBM_Line_Item_ID',
       'Total_Conversions', 'Total_Revenue', 'DBM_Revenue_Advertiser_Currency',
       'measurable_6060602', 'viewable_6066102', 'fraud_6065499',
       'HI_Quote_320052', 'HI_Sales_320053'],
      dtype='object')

---

In [279]:
oactivity = pd.read_csv("C:\\Users\\ylin\\Desktop\\ias file\\original_activity.csv")

C:\Users\ylin\AppData\Local\Continuum\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2717: DtypeWarning: Columns (10,37,38,39,40,45,47,48,51,53,56) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [280]:
oactivity["cTime"] = pd.to_datetime(oactivity["Event_Time"])

In [281]:
oactivity["cTime"] = oactivity["cTime"].astype("str")

In [282]:
oactivity.cTime = oactivity.cTime.str[:20]

In [283]:
oactivity["Event_User"] = oactivity.cTime + "_" + oactivity.User_ID

In [284]:
oactivity.head()

Event_Time                       User_ID  Advertiser_ID  Campaign_ID  \
0  1507279103422175  AMsySZYm0qlBhhrKuveCqplzoFG8        1268443     20334041   
1  1508834251029799  AMsySZZAnhAEoB2YCKFOT6LI1DzU        1268443     20334041   
2  1509100517621317  AMsySZbb2LWaWJoOnzFBU2tSiF5x        1268443     20334041   
3  1508937850041742  AMsySZawbOkGD6PbMbUBjeMgZHXW        1268443     20334041   
4  1507278946575818  AMsySZYneWxiAIk3BHjs6qzsOq_D        1268443     20334041   

       Ad_ID  Rendering_ID  Creative_Version  Site_ID_DCM  Placement_ID  \
0  405784226      74877651                 2       984668     205748492   
1  405784226      74877651                 2       984668     205748492   
2  405784226      74877651                 2       984668     205748492   
3  405784247      74877651                 2       984668     205802572   
4  405784247      74877651                 2       984668     205802572   

  Country_Code                        ...                          \
0           UK                        ...                           
1           UK                        ...                           
2           UK                        ...                           
3           UK                        ...                           
4           UK                        ...                           

  DBM_Media_Fee_4_USD  DBM_Media_Fee_5_Advertiser_Currency  \
0                   0                                    0   
1                   0                                    0   
2                   0                                    0   
3                   0                                    0   
4                   0                                    0   

   DBM_Media_Fee_5_Partner_Currency  DBM_Media_Fee_5_USD  \
0                                 0                    0   
1                                 0                    0   
2                                 0                    0   
3                                 0                    0   
4                                 0                    0   

   DBM_Media_Cost_Advertiser_Currency  DBM_Media_Cost_Partner_Currency  \
0                                   0                                0   
1                                   0                                0   
2                                   0                                0   
3                                   0                                0   
4                                   0                                0   

  DBM_Media_Cost_USD Country_ID                 cTime  \
0                  0        NaN  1970-01-18 10:41:19.   
1                  0        NaN  1970-01-18 11:07:14.   
2                  0        NaN  1970-01-18 11:11:40.   
3                  0        NaN  1970-01-18 11:08:57.   
4                  0        NaN  1970-01-18 10:41:18.   

                                          Event_User  
0  1970-01-18 10:41:19._AMsySZYm0qlBhhrKuveCqplzoFG8  
1  1970-01-18 11:07:14._AMsySZZAnhAEoB2YCKFOT6LI1DzU  
2  1970-01-18 11:11:40._AMsySZbb2LWaWJoOnzFBU2tSiF5x  
3  1970-01-18 11:08:57._AMsySZawbOkGD6PbMbUBjeMgZHXW  
4  1970-01-18 10:41:18._AMsySZYneWxiAIk3BHjs6qzsOq_D  

[5 rows x 108 columns]

In [285]:
oactivity["measurable_6060602"] = 0
oactivity["viewable_6066102"] = 0
oactivity["fraud_6065499"] = 0
oactivity["HI_Quote_320052"] = 0
oactivity["HI_Sales_320053"] = 0

In [286]:
oactivity.loc[oactivity.Activity_ID == 6060602, "measurable_6060602"] = 1
oactivity.loc[oactivity.Activity_ID == 6066102, "viewable_6066102"] = 1
oactivity.loc[oactivity.Activity_ID == 6065499, "fraud_6065499"] = 1
oactivity.loc[oactivity.Activity_ID == 320052, "HI_Quote_320052"] = 1
oactivity.loc[oactivity.Activity_ID == 320053, "HI_Sales_320053"] = 1

In [287]:
oactivity.head()

Event_Time                       User_ID  Advertiser_ID  Campaign_ID  \
0  1507279103422175  AMsySZYm0qlBhhrKuveCqplzoFG8        1268443     20334041   
1  1508834251029799  AMsySZZAnhAEoB2YCKFOT6LI1DzU        1268443     20334041   
2  1509100517621317  AMsySZbb2LWaWJoOnzFBU2tSiF5x        1268443     20334041   
3  1508937850041742  AMsySZawbOkGD6PbMbUBjeMgZHXW        1268443     20334041   
4  1507278946575818  AMsySZYneWxiAIk3BHjs6qzsOq_D        1268443     20334041   

       Ad_ID  Rendering_ID  Creative_Version  Site_ID_DCM  Placement_ID  \
0  405784226      74877651                 2       984668     205748492   
1  405784226      74877651                 2       984668     205748492   
2  405784226      74877651                 2       984668     205748492   
3  405784247      74877651                 2       984668     205802572   
4  405784247      74877651                 2       984668     205802572   

  Country_Code       ...        DBM_Media_Cost_Partner_Currency  \
0           UK       ...                                      0   
1           UK       ...                                      0   
2           UK       ...                                      0   
3           UK       ...                                      0   
4           UK       ...                                      0   

   DBM_Media_Cost_USD  Country_ID                 cTime  \
0                   0         NaN  1970-01-18 10:41:19.   
1                   0         NaN  1970-01-18 11:07:14.   
2                   0         NaN  1970-01-18 11:11:40.   
3                   0         NaN  1970-01-18 11:08:57.   
4                   0         NaN  1970-01-18 10:41:18.   

                                          Event_User  measurable_6060602  \
0  1970-01-18 10:41:19._AMsySZYm0qlBhhrKuveCqplzoFG8                   0   
1  1970-01-18 11:07:14._AMsySZZAnhAEoB2YCKFOT6LI1DzU                   0   
2  1970-01-18 11:11:40._AMsySZbb2LWaWJoOnzFBU2tSiF5x                   0   
3  1970-01-18 11:08:57._AMsySZawbOkGD6PbMbUBjeMgZHXW                   0   
4  1970-01-18 10:41:18._AMsySZYneWxiAIk3BHjs6qzsOq_D                   0   

  viewable_6066102 fraud_6065499  HI_Quote_320052  HI_Sales_320053  
0                0             0                1                0  
1                0             0                1                0  
2                0             0                1                0  
3                0             0                1                0  
4                0             0                1                0  

[5 rows x 113 columns]

In [289]:
oactivity.pivot_table(index="Event_User", values=["measurable_6060602","viewable_6066102", "HI_Sales_320053", "HI_Quote_320052"], aggfunc=np.sum).sort_values("HI_Quote_320052", ascending=False).to_csv("C:\\Users\\ylin\\Desktop\\ias file\\"+"ias stats.csv")

In [252]:
oactivity.columns

Index(['Event_Time', 'User_ID', 'Advertiser_ID', 'Campaign_ID', 'Ad_ID',
       'Rendering_ID', 'Creative_Version', 'Site_ID_DCM', 'Placement_ID',
       'Country_Code',
       ...
       'DBM_Media_Cost_Partner_Currency', 'DBM_Media_Cost_USD', 'Country_ID',
       'cTime', 'Event_User', 'measurable_6060602', 'viewable_6066102',
       'fraud_6065499', 'HI_Quote_320052', 'HI_Sales_320053'],
      dtype='object', length=113)

In [239]:
len(oactivity.DBM_Auction_ID.unique())

771

In [238]:
len(oactivity.Event_User)

139664

In [ ]:
oactivity.DBM_Insertion