In [1]:
import numpy as np

In [2]:
#nan is expressed as numpy.nan 
np.nan

nan

In [12]:
a = np.array([1, 2, 3, np.nan, np.nan, 5])

In [13]:
a

array([  1.,   2.,   3.,  nan,  nan,   5.])

In [14]:
#you can use compare for array to return boolean value
a == 1

array([ True, False, False, False, False, False], dtype=bool)

In [15]:
#however we wont be able to find nan as how above is used
a == np.nan

array([False, False, False, False, False, False], dtype=bool)

In [16]:
#to find out the nan value from the array we have to instead use this
#using np.isnan
np.isnan(a)

array([False, False, False,  True,  True, False], dtype=bool)

In [18]:
#then use above as a filter to return the value which is equal to nan
a[np.isnan(a)]

array([ nan,  nan])

In [19]:
#then replace them with a new value
a[np.isnan(a)] = 0
a

array([ 1.,  2.,  3.,  0.,  0.,  5.])

---

In [20]:
#how about inf? np.inf
#different to np.nan, array == np.inf can be used
np.inf

inf

In [37]:
b = np.array([[1, 2, 3, np.inf], [2, 3, np.nan, 5]])

In [38]:
b

array([[  1.,   2.,   3.,  inf],
       [  2.,   3.,  nan,   5.]])

In [39]:
#below will return correct boolean value, if it was np.nan it wouldn't
b == np.inf

array([[False, False, False,  True],
       [False, False, False, False]], dtype=bool)

In [40]:
#now replacing np.inf number using filter with 0
b[b == np.inf] = 0
b

array([[  1.,   2.,   3.,   0.],
       [  2.,   3.,  nan,   5.]])

In [42]:
#another way is using np.isinf() 
c = np.array([[1, 2, 3, np.inf], [2, 3, np.nan, 5]])
c

array([[  1.,   2.,   3.,  inf],
       [  2.,   3.,  nan,   5.]])

In [43]:
np.isinf(c)

array([[False, False, False,  True],
       [False, False, False, False]], dtype=bool)

In [45]:
#similarly using that as a filter 
c[np.isinf(c)] = 0
c

array([[  1.,   2.,   3.,   0.],
       [  2.,   3.,  nan,   5.]])

---

In [48]:
#use np.isfinite to test whether it's either nan or inf

In [49]:
d = np.array([[1, 2, 3, np.inf], [2, 3, np.nan, 5]])
d

array([[  1.,   2.,   3.,  inf],
       [  2.,   3.,  nan,   5.]])

In [50]:
np.isfinite(d)

array([[ True,  True,  True, False],
       [ True,  True, False,  True]], dtype=bool)

---

In [ ]:
#the standards sum, max, min won't work when dataset has nan in there
#in this case we use 
#nansum, nanmin, nanmax, 

In [63]:
g = np.array([[1, 2, 3, 4], [2, 3, np.nan, 5]])
g

array([[  1.,   2.,   3.,   4.],
       [  2.,   3.,  nan,   5.]])

In [68]:
np.nansum(g)

20.0

In [70]:
np.nanmin(g)

1.0

In [71]:
np.nanmax(g)

5.0

---