In [1]:
import numpy as np

In [4]:
aaa = np.arange(1, 13).reshape(3, 4)

In [5]:
aaa

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [12]:
b = aaa > 10

In [13]:
aaa[b]

array([11, 12])

In [16]:
#subsetting all the values filtered by b with 0
aaa[b] = 0
aaa

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10,  0,  0]])

---

In [18]:
x = np.arange(1,21).reshape(4, 5)
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [19]:
#transpose
x.transpose()

array([[ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19],
       [ 5, 10, 15, 20]])

---

In [ ]:
#above we explore array and matrix computation
#firstly we can't simply compute lists we have to change them into array or matrix

In [83]:
a = np.array([[1, 2], [3, 4]])
b = np.array([2, 3])

In [84]:
#then we can compute array using simple arithmic
a * b

array([[ 2,  6],
       [ 6, 12]])

In [78]:
np.dot(a, b)

array([ 8, 18])